name: Integration tests

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Setup streamr-docker-dev environment
        run: |
          sudo service mysql stop
          git clone https://github.com/streamr-dev/streamr-docker-dev.git
          sudo ifconfig docker0 10.200.10.1/24
          ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start --wait --except data-union-server

      - name: Run integration tests
        run: npm run test
        env:
          DEBUG=Streamr*
